### PR TITLE
Black formatter support

### LINKED ISSUE #81: Add black configuration
https://pypi.org/project/black/

### PR DESCRIPTION
**Pull request by hombit**
To be merged after #109 introducing `pre-commit` support

Fixes #81

### CODE REVIEW

**Comment by matwey** [comment]
The code-style is awful.

**Comment by hombit** [comment]
> The code-style is awful.

I agree, but the point that it is homogeneously awful.

**Comment by hombit** [comment]
> Can we use other code-formatter?

`black` looks like the current industry standard, and a lot of other tooling (like linters) compatible with it

**Comment by balodja** [comment]
That thing has a very strange taste. For example, look at [that line](https://github.com/snad-space/coniferest/pull/110/files#diff-3b63cb613626e7d787b8e63ced54267d5d18966f5fbc3795812573b4e50a942dR12). The formatter took out the sign, but left the leading zero. Purely "wut?"

**Comment by hombit** [comment]
Ok guys, it looks like you happy with it and I merge it today after rebasing with current master

**Pull request closed without merging**
