### PR TITLE
initial import of pariou.py: code for feature importance

### PR DESCRIPTION
**Pull request by ManuGangler**
Feedback welcomed !

### CODE REVIEW

**Comment by hombit** [comment]
@ManuGangler could you please write a user-level documentation with a description of this idea? We put code examples later, now we just need an algorithm description. Please put to a new RST file in `docs/` directory.

**Comment by matwey** [comment]
@hombit  I've explored a little how this can be implemented in Cython:

1. We need to introduce new data to `selectors`: number of samples in the current node.
2. Then the code would be something like the following:
```cython
    with nogil, parallel(num_threads=num_threads):
        trees = indices.shape[0] - 1

        for x_index in prange(data.shape[0], schedule='static'):
            for tree_index in range(trees):
                tree_offset = indices[tree_index]
                i = 0
                while True:
                    selector = selectors[tree_offset + i]
                    feature = selector.feature
                    if feature < 0:
                        break

                    if data[x_index, feature] <= selector.value:
                        i = selector.left
                    else:
                        i = selector.right

                    child_selector = selectors[tree_offset +i]
                    delta = 1 + 2 * log(child_selector.n_samples / selector.n_samples)

                    delta_sum[x_index, feature] += delta
                    hit_count[x_index, feature] += 1
```

We obtain two 2D-arrays `delta_sum` and `hit_count`. Then we have three options
1. `delta_sum / hit_count` will give us the signatures for every sample in considerations
2. `np.sum(delta_sum, axis=0) / np.sum(hit_count, axis=0)` will give us the properly averaged signature over the considered dataset
3. `np.sum(delta_sum, axis=1) / np.sum(hit_count, axis=1)` will give us something else...

**Comment by hombit** [comment]
@matwey it looks good to me. The only major problem I see that it would make our trees larger and could make building performance worse. I believe size problem is not so bad: we need 4 or even 2 bites (if we can restrict subsample size), which will fit into current alignment. For the second problem we need benchmarks, but again, it probably should be very cheap.

I opened issue #112 for benchmark support

One small technical question, do we have natural logarithm here, not binary?
`delta = 1 + 2 * log(child_selector.n_samples / selector.n_samples)`

**Comment by matwey** [comment]
The natural logarithm came from the expansion

2 (H(N) -1) = 2(log(N) + gamma - 1)

**Comment by ManuGangler** [comment]
I tried to update with a pariou.rst file... Not sure if I succeeded

**Comment by hombit** [comment]
Superseded by #115

**Pull request closed without merging**
